main:
  push:
    - docker:
        image: node:18
      imports: https://cnb.cool/godgodgame/oci-private-key/-/blob/main/envs.yml
      stages:
        - name: 环境检查
          script: echo $GITHUB_TOKEN_GK && echo $GITHUB_TOKEN && node -v && npm -v
        - name: 同步更新github
          script: git push https://$GITHUB_TOKEN_GK:$GITHUB_TOKEN@github.com/zhezzma/llm-for-office.git HEAD:main
